### ISSUE TITLE
I get a blank task list every time I add a new task

### ISSUE THREAD

**Issue by avierax** [mpcjanssen/simpletask-android#1015]
Every time I add a new task the app shows me a blank task list. 

![image](https://user-images.githubusercontent.com/4680369/64430618-9f667d80-d086-11e9-9050-d53a34db7b9c.png)

![image](https://user-images.githubusercontent.com/4680369/64430631-a68d8b80-d086-11e9-8135-b0b911417a89.png)

If I immediately reopen the task file again I can see the recently added task there. 
"... > Open Task List File > todo.txt that I can see my task list again." 

If I add yet another task without reopening the file I lost all my tasks, leaving the todo.txt file with only one entry, the last one.

SimpleTask Cloudless Version: 10.3.0
Android Version: 9

**Comment by mpcjanssen** [comment]
Could you add the log file from Settings->Other->Debug log?

**Comment by avierax** [comment]
I have just included the logs in the main description of the issue. 

Take a look.

**Comment by avierax** [comment]
I'm not using dropbox or any other cloud. I'm just using a cloudless version and a local file. I don't even have a dropbox account.

**Comment by mpcjanssen** [comment]
@avierax just to confirm, you are not modifying the task list in the background?

**Comment by mpcjanssen** [comment]
I think the background file monitoring is acting up, I will prepare a version without this later this week so you can test.

**Comment by avierax** [comment]
> 
> 
> @avierax just to confirm, you are not modifying the task list in the background?

No, not at all. In fact the task I add is being correctly shown up if I reopen the file.  

I'm using the application with a workaround. Everytime I add a new task I have to reopen the task list file.

All other actions work well: mark as done, delete.

**Comment by avierax** [comment]
UPDATE: The bug is also reproducible if I edit an already existing task. I'll update the issue description.

**Comment by mpcjanssen** [comment]
@avierax could you try with the debug build from https://www.mpcjanssen.nl/artifacts/bug-1015/app-cloudless-debug.apk ? You can install this next to the Playstore version.

**Comment by avierax** [comment]
Sorry for my late reply. I'm now installing the version you prepared. I'll
feedback as soon as I'm able.

**Comment by avierax** [comment]
```
--------- beginning of main
09-13 14:24:10.727 27449 27449 I impletask.debu: Late-enabling -Xcheck:jni
09-13 14:24:11.182 27449 27449 I Perf    : Connecting to perf service.
09-13 14:24:11.207 27449 27449 W impletask.debu: Accessing hidden method Landroid/text/SpannableStringInternal;->length()I (light greylist, linking)
09-13 14:24:11.277 27449 27449 I MultiDex: VM with version 2.1.0 has multidex support
09-13 14:24:11.277 27449 27449 I MultiDex: Installing application
09-13 14:24:11.277 27449 27449 I MultiDex: VM has multidex support, MultiDex support library is disabled.
09-13 14:24:11.330 27449 27449 D QueryStore: Saved applyFilter ids: []
09-13 14:24:11.372 27449 27449 I TodoApplication: onCreate()
09-13 14:24:11.372 27449 27449 I TodoApplication: Created todolist nl.mpcjanssen.simpletask.task.TodoList@6511f1f
09-13 14:24:11.373 27449 27449 I TodoApplication: Started Simpletask cloudless v10.3.0-DEBUG (3213)
09-13 14:24:11.402 27449 27449 I TodoApplication: Scheduling daily UI updateCache alarm, first at Sat Sep 14 00:02:00 GMT-04:00 2019
09-13 14:24:11.404 27449 27449 I TodoApplication: Scheduling task list reload
09-13 14:24:11.718 27449 27449 I Simpletask: onCreate
09-13 14:24:11.789 27449 27449 W impletask.debu: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
09-13 14:24:11.792 27449 27449 W impletask.debu: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
09-13 14:24:12.018 27449 27449 I FileStore: onCreate
09-13 14:24:12.020 27449 27449 I FileStore: Default path: /storage/emulated/0/data/nl.mpcjanssen.simpletask/todo.txt
09-13 14:24:12.032 27449 27449 I Simpletask: onResume
09-13 14:24:12.033 27449 27449 D TodoList: Reload: Main activity resume
09-13 14:24:12.033 27449 27449 I Util    : Sending file sync start broadcast
09-13 14:24:12.033 27449 27449 I Util    : Sending file sync done changed broadcast
09-13 14:24:12.034 27449 27449 I Simpletask: handleIntent: not authenticated
09-13 14:24:12.047 27449 27449 D Event   : update UI for event RESUME
09-13 14:24:12.058 27449 27449 E Util    : Lua error: bad argument: table expected, got nil )
09-13 14:24:12.058 27449 27449 D Simpletask: Update applyFilter bar
09-13 14:24:12.060 27449 27449 E Util    : Lua error: bad argument: table expected, got nil )
09-13 14:24:12.063 27449 27449 E Util    : Lua error: bad argument: table expected, got nil )
09-13 14:24:12.063 27449 27449 D Simpletask: Update applyFilter bar
09-13 14:24:12.064 27449 27449 E Util    : Lua error: bad argument: table expected, got nil )
09-13 14:24:12.095 27449 27449 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@eb54544
09-13 14:24:12.158 27449 27449 D OpenGLRenderer: Skia GL Pipeline
09-13 14:24:12.207 27449 27471 I Adreno  : QUALCOMM build                   : 2df12b3, I07da2d9908
09-13 14:24:12.207 27449 27471 I Adreno  : Build Date                       : 10/04/18
09-13 14:24:12.207 27449 27471 I Adreno  : OpenGL ES Shader Compiler Version: EV031.25.03.01
09-13 14:24:12.207 27449 27471 I Adreno  : Local Branch                     : 
09-13 14:24:12.207 27449 27471 I Adreno  : Remote Branch                    : 
09-13 14:24:12.207 27449 27471 I Adreno  : Remote Branch                    : 
09-13 14:24:12.207 27449 27471 I Adreno  : Reconstruct Branch               : 
09-13 14:24:12.207 27449 27471 I Adreno  : Build Config                     : S L 6.0.7 AArch64
09-13 14:24:12.207 27449 27471 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
09-13 14:24:12.214 27449 27471 I Adreno  : PFP: 0x005ff087, ME: 0x005ff063
09-13 14:24:12.218 27449 27471 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
09-13 14:24:12.218 27449 27471 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
09-13 14:24:12.219 27449 27471 I OpenGLRenderer: Initialized EGL, version 1.4
09-13 14:24:12.219 27449 27471 D OpenGLRenderer: Swap behavior 2
09-13 14:24:12.239 27449 27471 D vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
09-13 14:24:12.239 27449 27471 D vndksupport: Loading /vendor/lib64/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
09-13 14:24:17.473 27449 27449 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@8c581b1
09-13 14:24:17.482 27449 27449 I Simpletask: onCreate
09-13 14:24:17.686 27449 27449 I Simpletask: onResume
09-13 14:24:17.686 27449 27449 D TodoList: Reload: Main activity resume
09-13 14:24:17.686 27449 27449 I Util    : Sending file sync start broadcast
09-13 14:24:17.690 27449 27449 I FSQ     : -> Reload
09-13 14:24:17.695 27449 27449 I Util    : Sending file sync done changed broadcast
09-13 14:24:17.695 27449 27497 I FSQ     : <- Reload
09-13 14:24:17.696 27449 27497 I TodoList: Remote version is different, sync
09-13 14:24:17.696 27449 27497 I FileStore: Loading tasks
09-13 14:24:17.700 27449 27449 I Simpletask: handleIntent: from m_prefs state
09-13 14:24:17.700 27449 27497 E TodoList: TodoList load failed: {}/storage/emulated/0/data/nl.mpcjanssen.simpletask/todo.txt
09-13 14:24:17.700 27449 27497 E TodoList: java.io.FileNotFoundException: /storage/emulated/0/data/nl.mpcjanssen.simpletask/todo.txt (No such file or directory)
09-13 14:24:17.700 27449 27497 E TodoList:  at java.io.FileInputStream.open0(Native Method)
09-13 14:24:17.700 27449 27497 E TodoList:  at java.io.FileInputStream.open(FileInputStream.java:231)
09-13 14:24:17.700 27449 27497 E TodoList:  at java.io.FileInputStream.<init>(FileInputStream.java:165)
09-13 14:24:17.700 27449 27497 E TodoList:  at kotlin.io.FilesKt__FileReadWriteKt.forEachLine(FileReadWrite.kt:166)
09-13 14:24:17.700 27449 27497 E TodoList:  at kotlin.io.FilesKt__FileReadWriteKt.readLines(FileReadWrite.kt:195)
09-13 14:24:17.700 27449 27497 E TodoList:  at kotlin.io.FilesKt__FileReadWriteKt.readLines$default(FileReadWrite.kt:193)
09-13 14:24:17.700 27449 27497 E TodoList:  at nl.mpcjanssen.simpletask.remote.FileStore.loadTasksFromFile(FileStore.kt:44)
09-13 14:24:17.700 27449 27497 E TodoList:  at nl.mpcjanssen.simpletask.task.TodoList$reload$1.invoke(TodoList.kt:258)
09-13 14:24:17.700 27449 27497 E TodoList:  at nl.mpcjanssen.simpletask.task.TodoList$reload$1.invoke(TodoList.kt:21)
09-13 14:24:17.700 27449 27497 E TodoList:  at nl.mpcjanssen.simpletask.util.ActionQueue$add$1.invoke(ActionQueues.kt:16)
09-13 14:24:17.700 27449 27497 E TodoList:  at nl.mpcjanssen.simpletask.util.ActionQueue$add$1.invoke(ActionQueues.kt:9)
09-13 14:24:17.700 27449 27497 E TodoList:  at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt:143)
09-13 14:24:17.700 27449 27497 E TodoList:  at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Unknown Source:0)
09-13 14:24:17.700 27449 27497 E TodoList:  at org.jetbrains.anko.AsyncKt$sam$java_util_concurrent_Callable$0.call(Unknown Source:2)
09-13 14:24:17.700 27449 27497 E TodoList:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-13 14:24:17.700 27449 27497 E TodoList:  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
09-13 14:24:17.700 27449 27497 E TodoList:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-13 14:24:17.700 27449 27497 E TodoList:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-13 14:24:17.700 27449 27497 E TodoList:  at java.lang.Thread.run(Thread.java:764)
09-13 14:24:17.701 27449 27497 I TodoList: TodoList loaded from dropbox
09-13 14:24:17.701 27449 27449 I TaskAdapter: Text size = 14.0
09-13 14:24:17.701 27449 27449 I TaskAdapter: setFilteredTasks called: nl.mpcjanssen.simpletask.task.TodoList@6511f1f
09-13 14:24:17.702 27449 27449 D TodoList: Getting sorted and filtered tasks
09-13 14:24:17.711 27449 27449 D TodoList: Sorting and filtering tasks took 9 ms
09-13 14:24:17.737 27449 27449 D Simpletask: Scroll selection
09-13 14:24:17.737 27449 27449 D Event   : update UI for event RESUME
09-13 14:24:17.738 27449 27449 D Simpletask: Update applyFilter bar
09-13 14:24:17.740 27449 27449 D Simpletask: Update applyFilter bar
09-13 14:24:18.770 27449 27449 I Choreographer: Skipped 59 frames!  The application may be doing too much work on its main thread.
09-13 14:24:18.948 27449 27471 I OpenGLRenderer: Davey! duration=1174ms; Flags=0, IntendedVsync=1027732766974351, Vsync=1027733750307645, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1027733763484405, AnimationStart=1027733763603937, PerformTraversalsStart=1027733764295916, DrawStart=1027733764913103, SyncQueued=1027733908556905, SyncStart=1027733908867687, IssueDrawCommandsStart=1027733909036384, SwapBuffers=1027733939770968, FrameCompleted=1027733941515811, DequeueBufferDuration=9788000, QueueBufferDuration=652000, 
09-13 14:24:19.036 27449 27471 I OpenGLRenderer: Davey! duration=1262ms; Flags=0, IntendedVsync=1027732766974351, Vsync=1027733750307645, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1027733763484405, AnimationStart=1027733763603937, PerformTraversalsStart=1027733764295916, DrawStart=1027733944742582, SyncQueued=1027733952413832, SyncStart=1027733952804041, IssueDrawCommandsStart=1027733952936072, SwapBuffers=1027734027141280, FrameCompleted=1027734029383311, DequeueBufferDuration=5101000, QueueBufferDuration=1062000, 
09-13 14:24:19.068 27449 27449 I Simpletask: Recreating options menu
09-13 14:24:19.074 27449 27449 D Simpletask: Handle mode
09-13 14:24:22.967 27449 27471 D OpenGLRenderer: endAllActiveAnimators on 0x7a8910a600 (RippleDrawable) with handle 0x7a88e28dc0
09-13 14:24:24.577 27449 27449 W impletask.debu: Accessing hidden method Landroid/widget/PopupWindow;->setClipToScreenEnabled(Z)V (light greylist, reflection)
09-13 14:24:24.578 27449 27449 W impletask.debu: Accessing hidden method Landroid/widget/PopupWindow;->setEpicenterBounds(Landroid/graphics/Rect;)V (light greylist, reflection)
09-13 14:24:24.578 27449 27449 W impletask.debu: Accessing hidden method Landroid/widget/PopupWindow;->setTouchModal(Z)V (light greylist, reflection)
09-13 14:24:24.724 27449 27449 W impletask.debu: Accessing hidden field Landroid/widget/AbsListView;->mIsChildViewEnabled:Z (light greylist, reflection)
09-13 14:24:24.732 27449 27454 I impletask.debu: Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
09-13 14:24:26.603 27449 27449 I Simpletask: onMenuItemSelected: 2131296466
09-13 14:24:26.624 27449 27512 I FileDialog: File list from /storage/emulated/0/data/nl.mpcjanssen.simpletask loaded
09-13 14:24:29.139 27449 27516 I FileDialog: File list from /storage/emulated/0/data loaded
09-13 14:24:29.154 27449 27471 D OpenGLRenderer: endAllActiveAnimators on 0x7a8914a400 (AlertController$RecycleListView) with handle 0x7a88ec7640
09-13 14:24:30.257 27449 27471 D OpenGLRenderer: endAllActiveAnimators on 0x7a88410800 (AlertController$RecycleListView) with handle 0x7a8a57a240
09-13 14:24:30.273 27449 27517 I FileDialog: File list from /storage/emulated/0 loaded
09-13 14:24:33.235 27449 27522 I FileDialog: File list from /storage/emulated loaded
09-13 14:24:33.276 27449 27471 D OpenGLRenderer: endAllActiveAnimators on 0x7a8848f100 (AlertController$RecycleListView) with handle 0x7a88965b60
09-13 14:24:36.019 27449 27526 I FileDialog: File list from /storage loaded
09-13 14:24:36.034 27449 27471 D OpenGLRenderer: endAllActiveAnimators on 0x7a88566200 (AlertController$RecycleListView) with handle 0x7a885aaee0
09-13 14:24:37.468 27449 27449 I FileDialog: Selected entry 9016-4EF8, folder: true
09-13 14:24:37.502 27449 27471 D OpenGLRenderer: endAllActiveAnimators on 0x7a88441800 (AlertController$RecycleListView) with handle 0x7a888af380
09-13 14:24:37.505 27449 27527 I FileDialog: File list from /storage/9016-4EF8 loaded
09-13 14:24:39.106 27449 27449 I FileDialog: Selected entry @Docs, folder: true
09-13 14:24:39.120 27449 27528 I FileDialog: File list from /storage/9016-4EF8/@Docs loaded
09-13 14:24:39.163 27449 27471 D OpenGLRenderer: endAllActiveAnimators on 0x7a88638900 (AlertController$RecycleListView) with handle 0x7a8843c940
09-13 14:24:40.238 27449 27449 I FileDialog: Selected entry @GTD, folder: true
09-13 14:24:40.249 27449 27529 I FileDialog: File list from /storage/9016-4EF8/@Docs/@GTD loaded
09-13 14:24:40.256 27449 27471 D OpenGLRenderer: endAllActiveAnimators on 0x7a886deb00 (AlertController$RecycleListView) with handle 0x7a88fd66c0
09-13 14:24:42.795 27449 27449 I FileDialog: Selected entry todo.txt, folder: false
09-13 14:24:42.798 27449 27449 I TodoApplication: Loading todolist
09-13 14:24:42.799 27449 27449 D TodoList: Reload: from file switch
09-13 14:24:42.799 27449 27449 I Util    : Sending file sync start broadcast
09-13 14:24:42.801 27449 27449 I FSQ     : -> Reload
09-13 14:24:42.802 27449 27497 I FSQ     : <- Reload
09-13 14:24:42.802 27449 27449 I Util    : Sending file sync done changed broadcast
09-13 14:24:42.803 27449 27497 I TodoList: Remote version is different, sync
09-13 14:24:42.803 27449 27497 I FileStore: Loading tasks
09-13 14:24:42.820 27449 27471 D OpenGLRenderer: endAllActiveAnimators on 0x7a88770200 (AlertController$RecycleListView) with handle 0x7a890dc340
09-13 14:24:42.827 27449 27497 I FileStore: Read 44 lines from /storage/9016-4EF8/@Docs/@GTD/todo.txt
09-13 14:24:42.933 27449 27497 D TodoList: Fill todolist
09-13 14:24:43.014 27449 27497 D TodoList: Notified changed
09-13 14:24:43.014 27449 27497 D TodoList: Clear selection
09-13 14:24:43.015 27449 27497 I TodoList: TodoList loaded from dropbox
09-13 14:24:43.015 27449 27449 I Simpletask: Highligh selection
09-13 14:24:43.016 27449 27449 I TodoApplication: Received broadcast TASKLIST_CHANGED
09-13 14:24:43.021 27449 27449 I TodoApplication: Redrawing widgets 
09-13 14:24:43.022 27449 27449 I Simpletask: Tasklist changed, refiltering adapter
09-13 14:24:43.023 27449 27449 I TaskAdapter: Text size = 14.0
09-13 14:24:43.023 27449 27449 I TaskAdapter: setFilteredTasks called: nl.mpcjanssen.simpletask.task.TodoList@6511f1f
09-13 14:24:43.024 27449 27449 D TodoList: Getting sorted and filtered tasks
09-13 14:24:43.075 27449 27449 D TodoList: Sorting and filtering tasks took 51 ms
09-13 14:24:43.078 27449 27449 D Event   : update UI for event TASK_LIST_CHANGED
09-13 14:24:43.080 27449 27449 I Simpletask: Recreating options menu
09-13 14:24:43.080 27449 27449 D Simpletask: Handle mode
09-13 14:24:43.327 27449 27449 I TaskAdapter: Text size = 14.0
09-13 14:24:43.327 27449 27449 I TaskAdapter: setFilteredTasks called: nl.mpcjanssen.simpletask.task.TodoList@6511f1f
09-13 14:24:43.328 27449 27449 D TodoList: Getting sorted and filtered tasks
09-13 14:24:43.359 27449 27449 D TodoList: Sorting and filtering tasks took 31 ms
09-13 14:24:43.362 27449 27449 D Simpletask: Update applyFilter bar
09-13 14:24:43.364 27449 27449 D Simpletask: Update applyFilter bar
09-13 14:24:46.970 27449 27449 I Simpletask: onMenuItemSelected: 16908332
09-13 14:24:46.972 27449 27449 D Simpletask: Handle mode
09-13 14:24:47.415 27449 27449 I Simpletask: Recreating options menu
09-13 14:24:47.416 27449 27449 D Simpletask: Handle mode
09-13 14:24:48.920 27449 27449 I Simpletask: Recreating options menu
09-13 14:24:48.920 27449 27449 D Simpletask: Handle mode
09-13 14:24:50.653 27449 27449 I Simpletask: Starting addTask activity
09-13 14:24:50.655 27449 27449 D TodoList: Edit tasks
09-13 14:24:50.655 27449 27449 D TodoList: Start add/edit task activity
09-13 14:24:50.680 27449 27449 I Simpletask: Saving scroll offset 0, 0
09-13 14:24:50.690 27449 27449 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@c12d35d
09-13 14:24:50.707 27449 27449 D AddTask : onCreate()
09-13 14:24:50.710 27449 27449 I TodoApplication: Loading todolist
09-13 14:24:50.710 27449 27449 D TodoList: Reload: before adding tasks
09-13 14:24:50.710 27449 27449 I Util    : Sending file sync start broadcast
09-13 14:24:50.711 27449 27449 I FSQ     : -> Reload
09-13 14:24:50.712 27449 27534 I FSQ     : <- Reload
09-13 14:24:50.712 27449 27449 I Util    : Sending file sync done changed broadcast
09-13 14:24:50.712 27449 27534 I TodoList: Remote version is same, load from cache
09-13 14:24:50.744 27449 27534 I Config  : Getting 44 items todoList from cache
09-13 14:24:50.796 27449 27449 D AddTask : Fill addtask
09-13 14:24:50.908 27449 27449 I AssistStructure: Flattened final assist data: 2892 bytes, containing 1 windows, 11 views
09-13 14:24:56.784 27449 27449 I AddTask : Not adding empty line
09-13 14:24:56.819 27449 27449 I Simpletask: onResume
09-13 14:24:56.819 27449 27449 D TodoList: Reload: Main activity resume
09-13 14:24:56.819 27449 27449 I Util    : Sending file sync start broadcast
09-13 14:24:56.820 27449 27449 I FSQ     : -> Reload
09-13 14:24:56.820 27449 27497 I FSQ     : <- Reload
09-13 14:24:56.821 27449 27449 I Util    : Sending file sync done changed broadcast
09-13 14:24:56.821 27449 27497 I TodoList: Remote version is same, load from cache
09-13 14:24:56.822 27449 27449 I Simpletask: handleIntent: from m_prefs state
09-13 14:24:56.823 27449 27449 I TaskAdapter: Text size = 14.0
09-13 14:24:56.823 27449 27449 I TaskAdapter: setFilteredTasks called: nl.mpcjanssen.simpletask.task.TodoList@6511f1f
09-13 14:24:56.823 27449 27449 D TodoList: Getting sorted and filtered tasks
09-13 14:24:56.827 27449 27497 I Config  : Getting 44 items todoList from cache
09-13 14:24:56.842 27449 27449 D TodoList: Sorting and filtering tasks took 19 ms
09-13 14:24:56.844 27449 27449 I TaskAdapter: Restoring scroll offset 0, 0
09-13 14:24:56.849 27449 27449 D Simpletask: Scroll selection
09-13 14:24:56.849 27449 27449 D Event   : update UI for event RESUME
09-13 14:24:56.850 27449 27449 D Simpletask: Update applyFilter bar
09-13 14:24:56.852 27449 27449 D Simpletask: Update applyFilter bar
09-13 14:24:59.205 27449 27449 I Simpletask: onMenuItemSelected: 2131296475
09-13 14:24:59.237 27449 27449 I Simpletask: Saving scroll offset 0, 0
09-13 14:24:59.251 27449 27449 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@8f217d2
09-13 14:24:59.291 27449 27449 I Preferences: Registering broadcast receiver
09-13 14:24:59.548 27449 27471 D OpenGLRenderer: endAllActiveAnimators on 0x7a89143700 (MenuPopupWindow$MenuDropDownListView) with handle 0x7a86ca6ea0
09-13 14:25:03.020 27449 27537 D CalendarSync: Checking whether calendar sync is needed
09-13 14:25:05.052 27449 27449 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@4714c17
09-13 14:25:09.383 27449 27449 I Simpletask: onResume
09-13 14:25:09.383 27449 27449 D TodoList: Reload: Main activity resume
09-13 14:25:09.383 27449 27449 I Util    : Sending file sync start broadcast
09-13 14:25:09.384 27449 27449 I FSQ     : -> Reload
09-13 14:25:09.384 27449 27543 I FSQ     : <- Reload
09-13 14:25:09.385 27449 27449 I Util    : Sending file sync done changed broadcast
09-13 14:25:09.385 27449 27543 I TodoList: Remote version is same, load from cache
09-13 14:25:09.386 27449 27449 I Simpletask: handleIntent: from m_prefs state
09-13 14:25:09.387 27449 27449 I TaskAdapter: Text size = 14.0
09-13 14:25:09.387 27449 27449 I TaskAdapter: setFilteredTasks called: nl.mpcjanssen.simpletask.task.TodoList@6511f1f
09-13 14:25:09.387 27449 27449 D TodoList: Getting sorted and filtered tasks
09-13 14:25:09.391 27449 27543 I Config  : Getting 44 items todoList from cache
09-13 14:25:09.401 27449 27449 D TodoList: Sorting and filtering tasks took 14 ms
09-13 14:25:09.403 27449 27449 I TaskAdapter: Restoring scroll offset 0, 0
09-13 14:25:09.406 27449 27449 D Simpletask: Scroll selection
09-13 14:25:09.406 27449 27449 D Event   : update UI for event RESUME
09-13 14:25:09.407 27449 27449 D Simpletask: Update applyFilter bar
09-13 14:25:09.408 27449 27449 D Simpletask: Update applyFilter bar
09-13 14:25:10.586 27449 27449 I Simpletask: Starting addTask activity
09-13 14:25:10.588 27449 27449 D TodoList: Edit tasks
09-13 14:25:10.588 27449 27449 D TodoList: Start add/edit task activity
09-13 14:25:10.607 27449 27449 I Simpletask: Saving scroll offset 0, 0
09-13 14:25:10.620 27449 27449 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@aa2c373
09-13 14:25:10.629 27449 27449 D AddTask : onCreate()
09-13 14:25:10.632 27449 27449 I TodoApplication: Loading todolist
09-13 14:25:10.632 27449 27449 D TodoList: Reload: before adding tasks
09-13 14:25:10.632 27449 27449 I Util    : Sending file sync start broadcast
09-13 14:25:10.632 27449 27449 I FSQ     : -> Reload
09-13 14:25:10.633 27449 27534 I FSQ     : <- Reload
09-13 14:25:10.633 27449 27449 I Util    : Sending file sync done changed broadcast
09-13 14:25:10.633 27449 27534 I TodoList: Remote version is same, load from cache
09-13 14:25:10.639 27449 27534 I Config  : Getting 44 items todoList from cache
09-13 14:25:10.661 27449 27449 D AddTask : Fill addtask
09-13 14:25:10.773 27449 27449 I AssistStructure: Flattened final assist data: 2892 bytes, containing 1 windows, 11 views
09-13 14:25:13.288 27449 27449 I AddTask : Saving 1 tasks, updating [] tasks
09-13 14:25:13.289 27449 27449 D TodoList: Remove
09-13 14:25:13.289 27449 27449 D TodoList: Add task 1 atEnd: true
09-13 14:25:13.290 27449 27449 D TodoList: Notified changed
09-13 14:25:13.290 27449 27449 I Util    : Sending file sync start broadcast
09-13 14:25:13.297 27449 27449 I FSQ     : -> Save
09-13 14:25:13.299 27449 27449 D TodoList: Clear selection
09-13 14:25:13.299 27449 27580 I FSQ     : <- Save
09-13 14:25:13.300 27449 27449 I Util    : Sending widget refresh broadcast
09-13 14:25:13.301 27449 27449 D TodoList: Clear selection
09-13 14:25:13.310 27449 27580 I TodoList: Saving todo list, size 45
09-13 14:25:13.310 27449 27580 I FileStore: Saving tasks to file: /storage/9016-4EF8/@Docs/@GTD/todo.txt
09-13 14:25:13.314 27449 27449 I Simpletask: Highligh selection
09-13 14:25:13.314 27449 27449 I TodoApplication: Received broadcast UPDATE_WIDGETS
09-13 14:25:13.315 27449 27449 I TodoApplication: Refresh widgets from broadcast
09-13 14:25:13.316 27449 27449 I TodoApplication: Redrawing widgets 
09-13 14:25:13.331 27449 27449 I Simpletask: Recreating options menu
09-13 14:25:13.331 27449 27449 D Simpletask: Handle mode
09-13 14:25:13.350 27449 27449 I Simpletask: onResume
09-13 14:25:13.350 27449 27449 D TodoList: Reload: Main activity resume
09-13 14:25:13.350 27449 27449 I Util    : Sending file sync start broadcast
09-13 14:25:13.351 27449 27449 I FSQ     : -> Reload
09-13 14:25:13.351 27449 27497 I FSQ     : <- Reload
09-13 14:25:13.352 27449 27497 I TodoList: Remote version is different, sync
09-13 14:25:13.352 27449 27449 I Util    : Sending file sync done changed broadcast
09-13 14:25:13.353 27449 27449 I Simpletask: handleIntent: from m_prefs state
09-13 14:25:13.353 27449 27449 I TaskAdapter: Text size = 14.0
09-13 14:25:13.354 27449 27449 I TaskAdapter: setFilteredTasks called: nl.mpcjanssen.simpletask.task.TodoList@6511f1f
09-13 14:25:13.354 27449 27449 D TodoList: Getting sorted and filtered tasks
09-13 14:25:13.357 27449 27497 I Config  : Getting 45 items todoList from cache
09-13 14:25:13.366 27449 27449 D TodoList: Sorting and filtering tasks took 12 ms
09-13 14:25:13.367 27449 27449 I TaskAdapter: Restoring scroll offset 0, 0
09-13 14:25:13.370 27449 27449 D Simpletask: Scroll selection
09-13 14:25:13.371 27449 27449 D Event   : update UI for event RESUME
09-13 14:25:13.371 27449 27449 D Simpletask: Update applyFilter bar
09-13 14:25:13.372 27449 27449 D Simpletask: Update applyFilter bar
09-13 14:25:13.384 27449 27497 I FileStore: Loading tasks
09-13 14:25:13.385 27449 27497 I FileStore: Read 0 lines from /storage/9016-4EF8/@Docs/@GTD/todo.txt
09-13 14:25:13.385 27449 27497 D TodoList: Fill todolist
09-13 14:25:13.390 27449 27497 D TodoList: Notified changed
09-13 14:25:13.390 27449 27497 D TodoList: Clear selection
09-13 14:25:13.390 27449 27497 I TodoList: TodoList loaded from dropbox
09-13 14:25:13.473 27449 27580 I Util    : Sending file sync done changed broadcast
09-13 14:25:13.529 27449 27449 I Simpletask: Highligh selection
09-13 14:25:13.530 27449 27449 I TodoApplication: Received broadcast TASKLIST_CHANGED
09-13 14:25:13.530 27449 27449 I TodoApplication: Redrawing widgets 
09-13 14:25:13.531 27449 27449 I Simpletask: Tasklist changed, refiltering adapter
09-13 14:25:13.532 27449 27449 I TaskAdapter: Text size = 14.0
09-13 14:25:13.532 27449 27449 I TaskAdapter: setFilteredTasks called: nl.mpcjanssen.simpletask.task.TodoList@6511f1f
09-13 14:25:13.532 27449 27449 D TodoList: Getting sorted and filtered tasks
09-13 14:25:13.535 27449 27449 D TodoList: Sorting and filtering tasks took 3 ms
09-13 14:25:13.536 27449 27449 D Event   : update UI for event TASK_LIST_CHANGED
09-13 14:25:13.542 27449 27449 I Simpletask: Recreating options menu
09-13 14:25:13.542 27449 27449 D Simpletask: Handle mode
09-13 14:25:13.594 27449 27449 I TaskAdapter: Text size = 14.0
09-13 14:25:13.595 27449 27449 I TaskAdapter: setFilteredTasks called: nl.mpcjanssen.simpletask.task.TodoList@6511f1f
09-13 14:25:13.595 27449 27449 D TodoList: Getting sorted and filtered tasks
09-13 14:25:13.600 27449 27449 D TodoList: Sorting and filtering tasks took 5 ms
09-13 14:25:13.601 27449 27449 D Simpletask: Update applyFilter bar
09-13 14:25:13.603 27449 27449 D Simpletask: Update applyFilter bar
09-13 14:25:20.840 27449 27449 I Simpletask: onMenuItemSelected: 2131296475
09-13 14:25:20.884 27449 27449 I Simpletask: Saving scroll offset 0, 0
09-13 14:25:20.896 27449 27449 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@85bb376
09-13 14:25:20.927 27449 27449 I Preferences: Registering broadcast receiver
09-13 14:25:21.185 27449 27471 D OpenGLRenderer: endAllActiveAnimators on 0x7a8a774600 (MenuPopupWindow$MenuDropDownListView) with handle 0x7a87de6cc0
09-13 14:25:23.951 27449 27449 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@cc870fa
09-13 14:25:33.531 27449 27537 D CalendarSync: Checking whether calendar sync is needed
```

**Comment by mpcjanssen** [comment]
Somehow the file got cleared after simpletask saving it. I can't really think of a reason why. When you add some tasks to todo.txt and check the file later with some other program, are the tasks still there?

**Comment by mpcjanssen** [comment]
@avierax can you also try with Storage Framework version which is a work in progress. You can download a test build from: https://www.mpcjanssen.nl/artifacts/saf ? Be aware that installing this version will remove any widgets you might have so if you stille have a lot of widgets configured, don't install this. (or use the debug version)

**Comment by avierax** [comment]
No, the file is there and contains it's text also with the latest added
task. This is the only way I'm using the app now. I add a task using the
widget and never directly from the app to avoid this bug.

**Comment by mpcjanssen** [comment]
@avierax did you try with the version https://www.mpcjanssen.nl/artifacts/saf/app-release.apk

**Comment by avierax** [comment]
Just tried it. Works fine again. Just curious what was that?? 😃

**Comment by mpcjanssen** [comment]
Not sure really, but I think it had to do with the change listener. I will need to investigate further before this can go in the production version. But this at least gives me an idea where to look.

**Comment by mpcjanssen** [comment]
@avierax can you confirm this also works with 10.3.3 from the play store?

**Comment by avierax** [comment]
@mpcjanssen I have to test in my old phone. I have a Galaxy S9 and it seems
to work ok in it. (I have problems with writing to an SD Card though).

**Comment by mpcjanssen** [comment]
@avierax, right the play versions do not support writing to sd card. For that keep using the storageacessframework version.  I want to merge the cloudless version with this in the future.
