### ISSUE TITLE
Completing a task causes app to crash

### ISSUE THREAD

**Issue by sareporter** [mpcjanssen/simpletask-android#1053]
This is a new, bewildering problem on my Moto X4. When I try to complete a task, the app closes. When I re-open the app, the task is still there. Completing the task a second time is successful, but the app crashes. In my done file, the completed task is there twice.

Here's the log, thanks for any help you can offer ...

--------- beginning of crash
04-10 08:23:01.539 13015 13015 E AndroidRuntime: FATAL EXCEPTION: main
04-10 08:23:01.539 13015 13015 E AndroidRuntime: Process: nl.mpcjanssen.simpletask, PID: 13015
04-10 08:23:01.539 13015 13015 E AndroidRuntime: java.util.ConcurrentModificationException
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at java.util.ArrayList$Itr.next(ArrayList.java:860)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:1)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:1)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at kotlin.collections.CollectionsKt.joinToString$default(Unknown Source:0)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at nl.mpcjanssen.simpletask.util.Config.setTodoList(Config.kt:3)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at nl.mpcjanssen.simpletask.task.TodoList.save(TodoList.kt:4)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at nl.mpcjanssen.simpletask.task.TodoList.notifyTasklistChanged(TodoList.kt:2)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at nl.mpcjanssen.simpletask.task.TodoList.notifyTasklistChanged$default(TodoList.kt:1)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at nl.mpcjanssen.simpletask.Simpletask.completeTasks(Simpletask.kt:7)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at nl.mpcjanssen.simpletask.Simpletask.access$completeTasks(Simpletask.kt:1)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at nl.mpcjanssen.simpletask.Simpletask$updateCompletionCheckboxState$1.onMenuItemClick(Simpletask.kt:1)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:1)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:4)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:1)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:1)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:2)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at android.view.View.performClick(View.java:6597)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at android.view.View.performClickInternal(View.java:6574)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at android.view.View.access$3100(View.java:778)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at android.view.View$PerformClick.run(View.java:25906)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:873)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at android.os.Looper.loop(Looper.java:193)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6718)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
04-10 08:23:01.539 13015 13015 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
--------- beginning of main
04-10 09:58:20.873 14382 14382 I AlarmReceiver: Executing Alarm callback
04-10 09:58:20.874 14382 14382 I Util : Sending file changed broadcast
04-10 09:58:20.874 14382 14382 I TodoApplication: Received broadcast FILE_SYNC
04-10 09:58:20.874 14382 14382 I TodoApplication: Loading todolist
04-10 09:58:20.874 14382 14382 I FSQ : -> Reload
04-10 09:58:20.875 14382 16568 I FSQ : <- Reload
04-10 09:58:20.877 14382 16568 D TodoList: Reload: From BROADCAST_FILE_SYNC
04-10 09:58:20.899 14382 16568 D TodoList: Executing reloadaction
04-10 09:58:20.899 14382 16568 I Util : Sending file sync start broadcast
04-10 09:58:20.900 14382 16568 I TodoList: Remote version: 1586524938000 (current local 1586524938000)
04-10 09:58:20.900 14382 16568 I TodoList: Remote version is same, load from cache
04-10 09:58:20.900 14382 16568 I Util : Sending file sync done changed broadcast
04-10 10:08:52.138 14382 14382 I AlarmReceiver: Executing Alarm callback
04-10 10:08:52.138 14382 14382 I Util : Sending file changed broadcast
04-10 10:08:52.139 14382 14382 I TodoApplication: Received broadcast FILE_SYNC
04-10 10:08:52.139 14382 14382 I TodoApplication: Loading todolist
04-10 10:08:52.139 14382 14382 I FSQ : -> Reload
04-10 10:08:52.140 14382 14400 I FSQ : <- Reload
04-10 10:08:52.140 14382 14400 D TodoList: Reload: From BROADCAST_FILE_SYNC
04-10 10:08:52.141 14382 14400 D TodoList: Executing reloadaction
04-10 10:08:52.141 14382 14400 I Util : Sending file sync start broadcast
04-10 10:08:52.142 14382 14400 I TodoList: Remote version: 1586524938000 (current local 1586524938000)
04-10 10:08:52.142 14382 14400 I TodoList: Remote version is same, load from cache
04-10 10:08:52.142 14382 14400 I Util : Sending file sync done changed broadcast
04-10 10:20:23.852 14382 14382 I Simpletask: onNewIntent: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=nl.mpcjanssen.simpletask/.Simpletask bnds=[642,1579][846,1789] }
04-10 10:20:23.877 14382 14382 I Simpletask: onResume
04-10 10:20:23.877 14382 14382 I FSQ : -> Reload
04-10 10:20:23.878 14382 18492 I FSQ : <- Reload
04-10 10:20:23.878 14382 18492 D TodoList: Reload: Main activity resume
04-10 10:20:23.878 14382 14382 I Simpletask: onResume -> handleIntent
04-10 10:20:23.879 14382 18492 D TodoList: Executing reloadaction
04-10 10:20:23.879 14382 18492 I Util : Sending file sync start broadcast
04-10 10:20:23.879 14382 18492 I TodoList: Remote version: 1586531830000 (current local 1586524938000)
04-10 10:20:23.879 14382 18492 I TodoList: Remote version is different, sync
04-10 10:20:23.879 14382 18492 I FileStore: Loading tasks
04-10 10:20:23.895 14382 14382 I Simpletask: handleIntent: from m_prefs state
04-10 10:20:23.912 14382 14382 I TaskAdapter: Text size = 24.0
04-10 10:20:23.913 14382 14382 I TaskAdapter: setFilteredTasks called: nl.mpcjanssen.simpletask.task.TodoList@16457a
04-10 10:20:23.913 14382 14382 D TodoList: Getting sorted and filtered tasks
04-10 10:20:23.921 14382 18492 I FileStore: Read 489 lines from /storage/emulated/0/Syncthing/To do/A1 to do.txt
04-10 10:20:23.921 14382 18492 I FileStore: Observer: adding folder watcher on /storage/emulated/0/Syncthing/To do
04-10 10:20:23.923 14382 18492 I FileWatchService: Observer: creating observer on: {}
04-10 10:20:23.923 14382 18492 I FileStore: Observer: modifying done
04-10 10:20:23.955 14382 14382 D TodoList: Sorting and filtering tasks took 42 ms
04-10 10:20:23.957 14382 14382 I TaskAdapter: Restoring scroll offset 23, -262
04-10 10:20:23.957 14382 14382 I Simpletask: onResume <- handleIntent
04-10 10:20:23.958 14382 14382 D Event : update UI for event RESUME
04-10 10:20:23.958 14382 14382 D Simpletask: Update applyFilter bar
04-10 10:20:23.965 14382 14382 D Simpletask: Update applyFilter bar
04-10 10:20:24.246 14382 18492 D TodoList: Fill todolist with 489 items
04-10 10:20:24.246 14382 18492 I TodoList: Updating cache with remote version 1586531830000
04-10 10:20:24.246 14382 18492 I Config : Updating todoList cache with 489 items
04-10 10:20:24.260 14382 18492 I FSQ : -> Backup
04-10 10:20:24.261 14382 15204 I FSQ : <- Backup
04-10 10:20:24.261 14382 18492 D TodoList: Notified changed
04-10 10:20:24.261 14382 18492 D TodoList: Clear selection
04-10 10:20:24.263 14382 18492 I TodoList: TodoList loaded from filestore
04-10 10:20:24.263 14382 18492 I Util : Sending file sync done changed broadcast
04-10 10:20:24.263 14382 14382 I Simpletask: Highligh selection
04-10 10:20:24.263 14382 14382 I TodoApplication: Received broadcast TASKLIST_CHANGED
04-10 10:20:24.267 14382 14382 I TodoApplication: Redrawing widgets
04-10 10:20:24.267 14382 14382 D MyAppWidgetProvider: onUpdate 26
04-10 10:20:24.275 14382 14382 I TodoApplication: Updating widget: 26
04-10 10:20:24.275 14382 14382 I Simpletask: Tasklist changed, refiltering adapter
04-10 10:20:24.276 14382 14382 I TaskAdapter: Text size = 24.0
04-10 10:20:24.276 14382 14382 I TaskAdapter: setFilteredTasks called: nl.mpcjanssen.simpletask.task.TodoList@16457a
04-10 10:20:24.276 14382 14382 D TodoList: Getting sorted and filtered tasks
04-10 10:20:24.308 14382 14382 D TodoList: Sorting and filtering tasks took 32 ms
04-10 10:20:24.309 14382 14382 I TaskAdapter: Restoring scroll offset 23, -262
04-10 10:20:24.309 14382 14382 D Event : update UI for event TASK_LIST_CHANGED
04-10 10:20:24.310 14382 14382 I Simpletask: Recreating options menu
04-10 10:20:24.311 14382 14382 D Simpletask: Handle mode
04-10 10:20:24.320 14382 15204 D Util : Backing up of tasks took 59 ms
04-10 10:20:24.355 14382 14382 I TaskAdapter: Text size = 24.0
04-10 10:20:24.355 14382 14382 I TaskAdapter: setFilteredTasks called: nl.mpcjanssen.simpletask.task.TodoList@16457a
04-10 10:20:24.356 14382 14382 D TodoList: Getting sorted and filtered tasks
04-10 10:20:24.404 14382 14382 D TodoList: Sorting and filtering tasks took 48 ms
04-10 10:20:24.405 14382 14382 I TaskAdapter: Restoring scroll offset 23, -262
04-10 10:20:24.406 14382 14382 D Simpletask: Update applyFilter bar
04-10 10:20:24.408 14382 14382 D Simpletask: Update applyFilter bar
04-10 10:20:29.266 14382 14382 I Simpletask: onMenuItemSelected: 2131296555
04-10 10:20:29.312 14382 14382 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@2faa540
04-10 10:20:29.344 14382 14382 I Preferences: Registering broadcast receiver
04-10 10:20:34.057 14382 14382 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@a5ec7ad

**Comment by mpcjanssen** [comment]
@sareporter what is your time before save? And does changing it work around the issue?

**Comment by mpcjanssen** [comment]
Core issue is TodoList.save iterating directly over todoItems

**Comment by sareporter** [comment]
It was set on "3." I tried lowering and raising it and it didn't solve the problem.

For now I just turned off auto-archive and it works fine. Thanks ...

**Comment by mpcjanssen** [comment]
Ah auto archive probably is the trigger for the problem. I will see if I can reproduce and create a fix.

**Comment by mpcjanssen** [comment]
@sareporter can you check with one of the versions from https://www.mpcjanssen.nl/artifacts/10.5.3-17-37168c7/ ?

If you installed from Google play, you'll need the release version.

**Comment by taylor-josh** [comment]
I had this issue the other day after the latest fDroid release actually. I made a backup of my to-do file and then cleared the cache and data for the app and that fixed it. Not sure if that is helpful in this situation. If I encounter the problem again, I'll respond back.

**Comment by sareporter** [comment]
> @sareporter can you check with one of the versions from https://www.mpcjanssen.nl/artifacts/10.5.3-17-37168c7/ ?
> 
> If you installed from Google play, you'll need the release version.

Sorry, I just saw this. Looks like the problem was fixed in the latest update on F-Droid. I haven't had any issues. Thanks for jumping on this.
