### ISSUE TITLE
the app throws  IllegalArgumentException when importing wrong type file

### ISSUE THREAD

**Issue by androidAppGuard** [mpcjanssen/simpletask-android#1172]
**the environment is as follows:**
```
App version: 10.9.0
Android version: 6.0
Device: Nexux_5X
```
**The steps to reproduce:**
![29_simpletask_IllegalArgumentException.gif](https://s2.loli.net/2022/05/14/SWfCoTBz2uMIwHE.gif)
**The exception log is as follows:**
```
05-14 09:47:12.120 18497-18519/nl.mpcjanssen.simpletask.debug D/LeakCanary: HeapAnalysisFailure(heapDumpFile=/data/user/0/nl.mpcjanssen.simpletask.debug/files/leakcanary/2022-05-14_09-47-12_103.hprof, createdAtTimeMillis=1652521632119, analysisDurationMillis=6, exception=
    java.lang.IllegalArgumentException: Unsupported Hprof version [����] not in supported list [JAVA PROFILE 1.0, JAVA PROFILE 1.0.1, JAVA PROFILE 1.0.2, JAVA PROFILE 1.0.3]
        at shark.Hprof$Companion.open(Hprof.kt:82)
        at shark.HeapAnalyzer.analyze(HeapAnalyzer.kt:98)
        at leakcanary.internal.HeapAnalyzerService.onHandleIntentInForeground(HeapAnalyzerService.kt:61)
        at leakcanary.internal.ForegroundService.onHandleIntent(ForegroundService.kt:55)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by mpcjanssen** [comment]
This seems to be a leak canary issue more than a simpletask issue. I use the leak canary library as is so not much I can do about it.

**Comment by androidAppGuard** [comment]
Thanks, I got it, it a bug about canary library.
