### ISSUE TITLE
Out of bounds exception via google play

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#148]
java.lang.IndexOutOfBoundsException: setSpan (110 ... 110) ends beyond length 109
at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1044)
at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:614)
at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:610)
at android.text.Selection.setSelection(Selection.java:116)
at android.widget.EditText.setSelection(EditText.java:116)
at nl.mpcjanssen.simpletask.AddTask.replaceThresholdDate(AddTask.java:678)
at nl.mpcjanssen.simpletask.AddTask.replaceDate(AddTask.java:497)
at nl.mpcjanssen.simpletask.AddTask.insertDateAtSelection(AddTask.java:502)
at nl.mpcjanssen.simpletask.AddTask.access$600(AddTask.java:79)
at nl.mpcjanssen.simpletask.AddTask$9$1.onDateSet(AddTask.java:477)
at android.app.DatePickerDialog.tryNotifyDateSet(DatePickerDialog.java:207)
at android.app.DatePickerDialog.onClick(DatePickerDialog.java:161)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5335)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
at dalvik.system.NativeStart.main(Native Method)

**Comment by mpcjanssen** [comment]
this happens if you change the threshold date while the cursor is at the last position
