### ISSUE TITLE
CalendarSync exception

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#324]
The following exception was reported via Google:

````
java.lang.RuntimeException: Unable to create application nl.mpcjanssen.simpletask.TodoApplication: java.lang.IllegalArgumentException: Unknown URL content://com.android.calendar/calendars?caller_is_syncadapter=true&account_name=Simpletask%20Calendar&account_type=LOCAL
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4596)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:668)
	at android.app.ActivityThread.handleBindApplication(<Xposed>)
	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
Caused by: java.lang.IllegalArgumentException: Unknown URL content://com.android.calendar/calendars?caller_is_syncadapter=true&account_name=Simpletask%20Calendar&account_type=LOCAL
	at android.content.ContentResolver.insert(ContentResolver.java:1203)
	at nl.mpcjanssen.simpletask.CalendarSync.addCalendar(CalendarSync.java:118)
	at nl.mpcjanssen.simpletask.CalendarSync.setSyncType(CalendarSync.java:242)
	at nl.mpcjanssen.simpletask.CalendarSync.<init>(CalendarSync.java:264)
	at nl.mpcjanssen.simpletask.TodoApplication.onCreate(TodoApplication.java:113)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4593)
	... 13 more
````

**Comment by vojtechkral** [comment]
Thanks for info, will have a look at it asap...

**Comment by vojtechkral** [comment]
Can you find out what was the user's SDK version?

**Comment by mpcjanssen** [comment]
Android 5.1 with xposed on a note 2. So almost certainly cm12.1

**Comment by mpcjanssen** [comment]
So that's api level  22

**Comment by vojtechkral** [comment]
I'm not sure how this could happen, maybe it's xposed+xprivacy refusing access to calendar URL. Anyway, I'll add an exception handler just to be on the safe side...
