### ISSUE TITLE
Crash in updateLists (Playstore)

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#430]
```
java.lang.UnsupportedOperationException: Empty iterable can't be reduced.
	at nl.mpcjanssen.simpletask.Simpletask.updateItemsDialog(Simpletask.kt:1703)
	at nl.mpcjanssen.simpletask.Simpletask.updateLists(Simpletask.kt:1621)
	at nl.mpcjanssen.simpletask.Simpletask.access$updateLists(Simpletask.kt:63)
	at nl.mpcjanssen.simpletask.Simpletask$openSelectionMode$1.onMenuItemClick(Simpletask.kt:1206)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:169)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:760)
	at android.support.v7.view.menu.f.a(MenuBuilder.java:811)
	at android.support.v7.view.menu.h.a(MenuItemImpl.java:152)
	at android.support.v7.view.menu.f.a(MenuBuilder.java:958)
	at android.support.v7.view.menu.f.a(MenuBuilder.java:948)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
	at android.view.View.performClick(View.java:5204)
	at android.view.View$PerformClick.run(View.java:21155)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5422)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by mpcjanssen** [comment]
Fixed by 59d81b7800646583be514bdf6d491a8670bde0b8
