### ISSUE TITLE
Crash if no calendar content provider on device

### ISSUE THREAD

**Issue by mpcjanssen** [mpcjanssen/simpletask-android#446]
```
java.lang.RuntimeException: Unable to create application nl.mpcjanssen.simpletask.TodoApplication: java.lang.IllegalArgumentException: Unknown URL content://com.android.calendar/calendars?caller_is_syncadapter=true&account_name=Simpletask%20Calendar&account_type=LOCAL
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4476)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5146)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Unknown URL content://com.android.calendar/calendars?caller_is_syncadapter=true&account_name=Simpletask%20Calendar&account_type=LOCAL
	at android.content.ContentResolver.insert(ContentResolver.java:1186)
	at nl.mpcjanssen.simpletask.CalendarSync.addCalendar(CalendarSync.java:118)
	at nl.mpcjanssen.simpletask.CalendarSync.setSyncType(CalendarSync.java:242)
	at nl.mpcjanssen.simpletask.CalendarSync.<init>(CalendarSync.java:264)
	at nl.mpcjanssen.simpletask.TodoApplication.onCreate(TodoApplication.java:113)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)
	... 14 more
```

**Comment by vojtechkral** [comment]
Eh, some xposed hackery it seems.

**Comment by mpcjanssen** [comment]
I don't think this is caused by xposed per se. Simpletask should not crash if there is no `com.android.calender` content provider. But low prio.

**Comment by vojtechkral** [comment]
Well it needs to be fixed either way...
