### ISSUE TITLE
latest update (13 oct 2018) - now cannot connect to nextcloud webdav todo.txt

### ISSUE THREAD

**Issue by jet52** [mpcjanssen/simpletask-android#930]
Was using simpletask nextcloud for awhile. 
Latest update wiped login credentials, I see that in the changelog.
When entering server URL and user/password, I get only Login failed: FILE_NOT_FOUND
I don't have an image of what exactly I had before, but in nextcloud settings, it shows
my server as https://cloud.xxx.com/remote.php/webdav/
So I enter into simpletask https://cloud.xxx.com/remote.php/webdav/Documents/todo.txt
which reflect where my todo.txt file is stored.
I only get the FILE_NOT_FOUND error.
Any hints from anyone on this?

**Comment by smichel17** [comment]
I've been having some issues with nextcloud itself recently, though I suspect it may be my own problem (ssl cert issue).

**Comment by mpcjanssen** [comment]
Try  `https://cloud.xxx.com/` as the url

**Comment by jet52** [comment]
with just the base URL https://cloud.xxx.com/ I get a login failed HOST_NOT_AVAILABLE.  with the the file URL including remote.php/dir/todo.txt I get login failed FILE_NOT_FOUND.
I can login to this nextcloud using the mobile browser and other apps, just no longer with simpletask-nextcloud.  thanks for looking into this.  I had found the app quite useful so far.

log is below:

--------- beginning of system
10-15 13:26:01.818 10288 10288 D TextClassificationManager: Initialized SystemTextClassifier
10-15 13:26:01.819 10288 10288 W androidtc: TextClassifier called on main thread
10-15 13:26:10.897 10288 10288 I chatty  : uid=10267(nl.mpcjanssen.simpletask.nextcloud) identical 6 lines
10-15 13:26:10.977 10288 10288 W androidtc: TextClassifier called on main thread
--------- beginning of main
10-15 13:33:18.492 10288 10288 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@f951d0a
10-15 13:37:06.053 10288 10288 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
10-15 13:37:06.053 10288 10288 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
10-15 13:37:07.156 10288 10288 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
10-15 13:37:07.156 10288 10288 E SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
10-15 13:37:10.228 10288 10288 I FSQ     : -> login
10-15 13:37:10.229 10288 10303 I FSQ     : <- login
10-15 13:37:10.233 10288 10303 D OwnCloudClient #3: Creating OwnCloudClient
10-15 13:37:10.245 10288 10303 D OwnCloudClient #3: REQUEST PROPFIND //remote.php/webdav/
10-15 13:37:10.249 10288 10303 D AdvancedSslSocketFactory: Creating SSL Socket with remote 1cloud.tufte.net:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@a8b7457
10-15 13:37:10.249 10288 10303 D AdvancedSslSocketFactory:  ... with connection timeout 60000 and socket timeout 60000
10-15 13:37:10.252 10288 10303 I ServerNameIndicator: SSLSocket implementation: com.android.org.conscrypt.Java8FileDescriptorSocket
10-15 13:37:10.253 10288 10303 I ServerNameIndicator: SNI done, hostname: 1cloud.tufte.net
10-15 13:37:11.505 10288 10303 E ReadRemoteFolderOperation: Synchronized /: Unexpected exception
10-15 13:37:11.505 10288 10303 E ReadRemoteFolderOperation: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
10-15 13:37:11.505 10288 10303 E ReadRemoteFolderOperation: at com.owncloud.android.lib.common.network.WebdavEntry.<init>(WebdavEntry.java:87)
10-15 13:37:11.505 10288 10303 E ReadRemoteFolderOperation: at com.owncloud.android.lib.resources.files.ReadRemoteFolderOperation.readData(ReadRemoteFolderOperation.java:144)
10-15 13:37:11.505 10288 10303 E ReadRemoteFolderOperation: at com.owncloud.android.lib.resources.files.ReadRemoteFolderOperation.run(ReadRemoteFolderOperation.java:87)
10-15 13:37:11.505 10288 10303 E ReadRemoteFolderOperation: at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145)
10-15 13:37:11.505 10288 10303 E ReadRemoteFolderOperation: at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149)
10-15 13:37:11.505 10288 10303 E ReadRemoteFolderOperation: at nl.mpcjanssen.simpletask.remote.LoginScreen$startLogin$1.invoke(LoginScreen.kt:86)
10-15 13:37:11.505 10288 10303 E ReadRemoteFolderOperation: at nl.mpcjanssen.simpletask.remote.LoginScreen$startLogin$1.invoke(LoginScreen.kt:24)
10-15 13:37:11.505 10288 10303 E ReadRemoteFolderOperation: at nl.mpcjanssen.simpletask.util.ActionQueue$sam$java_lang_Runnable$0.run(Unknown Source:2)
10-15 13:37:11.505 10288 10303 E ReadRemoteFolderOperation: at nl.mpcjanssen.simpletask.util.LoggingRunnable.run(ActionQueues.kt:48)
10-15 13:37:11.505 10288 10303 E ReadRemoteFolderOperation: at android.os.Handler.handleCallback(Handler.java:873)
10-15 13:37:11.505 10288 10303 E ReadRemoteFolderOperation: at android.os.Handler.dispatchMessage(Handler.java:99)
10-15 13:37:11.505 10288 10303 E ReadRemoteFolderOperation: at android.os.Looper.loop(Looper.java:193)
10-15 13:37:11.505 10288 10303 E ReadRemoteFolderOperation: at nl.mpcjanssen.simpletask.util.ActionQueue.run(ActionQueues.kt:15)
10-15 13:37:11.505 10288 10303 D LoginScreen: Unexpected exception
10-15 13:37:11.505 10288 10303 D LoginScreen: length=1; index=1
10-15 13:37:11.505 10288 10303 D LoginScreen: -1
10-15 13:37:11.506 10288 10303 D LoginScreen: Login failed: HOST_NOT_AVAILABLE
10-15 13:37:13.085 10288 10288 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@5ba904d
- - -
Jerod Tufte

**Comment by jet52** [comment]
Now it works. Thanks for the troubleshooting.  I appreciate the clean simple app. 

Sent from Nine
________________________________

**Comment by mpcjanssen** [comment]
Thanks for confirming. Next release will remove any trailing /-es in the hostname.
