### ISSUE TITLE
HOST_NOT_AVAILABLE when logging in

### ISSUE THREAD

**Issue by jose1711** [mpcjanssen/simpletask-android#974]
i am getting HOST_NOT_AVAILABLE error when logging in to my personal nextcloud server. server is up and works fine with browser and in official android nextcloud client.

**Comment by Henry78** [comment]
This are the relevant log entries:

```
05-28 10:16:07.307  8854  8854 I FSQ     : -> login
05-28 10:16:07.313  8854 12736 I FSQ     : <- login
05-28 10:16:07.323  8854 12736 D NetworkUtils: Searching known-servers store at /data/user/0/nl.mpcjanssen.simpletask.nextcloud/files/knownServers.bks
05-28 10:16:07.325  8854 12736 D NetworkSecurityConfig: No Network Security Config specified, using platform default
05-28 10:16:07.338  8854 12736 D OwnCloudClient #0: Creating OwnCloudClient
05-28 10:16:07.353  8854 12736 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
05-28 10:16:07.353  8854 12736 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
05-28 10:16:07.353  8854 12736 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
05-28 10:16:07.468  8854  8860 I zygote64: Do partial code cache collection, code=30KB, data=20KB
05-28 10:16:07.470  8854  8860 I zygote64: After code cache collection, code=29KB, data=20KB
05-28 10:16:07.470  8854 12736 D OwnCloudClient #0: REQUEST PROPFIND /remote.php/webdav/
05-28 10:16:07.470  8854  8860 I zygote64: Increasing code cache capacity to 128KB
05-28 10:16:07.477  8854 12736 D AdvancedSslSocketFactory: Creating SSL Socket with remote nc.henry78.at:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@5cfcea6
05-28 10:16:07.478  8854 12736 D AdvancedSslSocketFactory:  ... with connection timeout 60000 and socket timeout 60000
05-28 10:16:07.483  8854 12736 I ServerNameIndicator: SSLSocket implementation: com.android.org.conscrypt.OpenSSLSocketImpl
05-28 10:16:07.485  8854 12736 I ServerNameIndicator: SNI done, hostname: nc.henry78.at
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: Synchronized /: Unexpected exception
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at com.owncloud.android.lib.common.network.WebdavEntry.<init>(WebdavEntry.java:308)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.readData(ReadFolderRemoteOperation.java:144)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at com.owncloud.android.lib.resources.files.ReadFolderRemoteOperation.run(ReadFolderRemoteOperation.java:88)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:145)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:149)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at nl.mpcjanssen.simpletask.remote.LoginScreen$startLogin$1.invoke(LoginScreen.kt:84)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at nl.mpcjanssen.simpletask.remote.LoginScreen$startLogin$1.invoke(LoginScreen.kt:24)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at nl.mpcjanssen.simpletask.util.ActionQueue$add$1.invoke(ActionQueues.kt:16)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at nl.mpcjanssen.simpletask.util.ActionQueue$add$1.invoke(ActionQueues.kt:9)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt:143)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Unknown Source:0)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at org.jetbrains.anko.AsyncKt$sam$java_util_concurrent_Callable$0.call(Unknown Source:2)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
05-28 10:16:08.307  8854 12736 E ReadFolderRemoteOperation: 	at java.lang.Thread.run(Thread.java:764)
05-28 10:16:08.308  8854 12736 D LoginScreen: Unexpected exception
05-28 10:16:08.308  8854 12736 D LoginScreen: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
05-28 10:16:08.308  8854 12736 D LoginScreen: -1
05-28 10:16:08.311  8854 12736 D LoginScreen: Login failed: HOST_NOT_AVAILABLE
05-28 10:16:10.039  8854  8860 I zygote64: Do partial code cache collection, code=52KB, data=41KB
05-28 10:16:10.039  8854  8860 I zygote64: After code cache collection, code=52KB, data=41KB
05-28 10:16:10.039  8854  8860 I zygote64: Increasing code cache capacity to 256KB
05-28 10:16:10.119  8854  8873 D OpenGLRenderer: endAllActiveAnimators on 0x701ffa1400 (RippleDrawable) with handle 0x701ef1df00
```

**Comment by jose1711** [comment]
@Henry78 so you're seeing the same issue? for the record it works fine on another owncloud (not Nextcloud) instance

**Comment by Henry78** [comment]
Not sure, but I get the same "HOST_NOT_AVAILABLE" error. 

My Nextcloud-Instance is a  16.0.1 That works from Browser, other Tools that sync via WebDav. The Logs show that there's no network issue. Hmm...

**Comment by Henry78** [comment]
This also happens with a fresh user (account) on my Nextcloud instance.

**Comment by mpcjanssen** [comment]
The host not found error could be a red herring masking an actual runtime error in the nextcloud lib. It would help immensely of someone with this issue could run a debug build in an ide and check the stack trace when this happens.

**Comment by jose1711** [comment]
Hey Mark, would it help if I make you a test account on my Nextcloud server? I think it could save some time - especially if you have a working IDE already. Thanks!

**Comment by mpcjanssen** [comment]
@jose1711 that would definitely help, i don't know when i can really look into it though.

**Comment by mpcjanssen** [comment]
I am able to reproduce it. The error is indeed a red herring, there is something else going on. Will look into this as soon as I have time.

**Comment by mpcjanssen** [comment]
Latest builds at https://mpcjanssen.nl/artifacts should have this issue fixed. @Henry78 can you also confirm?

**Comment by lamalediction** [comment]
It works for me!

**Comment by Henry78** [comment]
Yes, lates build works.

**Comment by jose1711** [comment]
Thank you again Mark, closing

**Comment by rcuddy** [comment]
Works for me too. Thanks heaps.

**Comment by Fire-Dragon-DoL** [comment]
I'm not sure if the build has already been pushed on android but I have the same situation. Didn't change anything on server and android app for months, now I get "ssl initialization failed" out of the blue. Terrible timing because i'm on a trip 😂

**Comment by mpcjanssen** [comment]
Build is not published yet, but you can download the nextcloid release  version from the message above.

**Comment by mpcjanssen** [comment]
@Fire-Dragon-DoL could you copy the debug log (from settings->other) ?

**Comment by Fire-Dragon-DoL** [comment]
Thanks for the indication,I'll post one as soon as I can (i'm on a trip), i want to do a few more checks on the server to see if nextcloud could be the problem
